server:
  port: 7002
  error:
    include-message: always

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: recommendation-db

logging:
  level:
    root: INFO
    com.kimsang: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

---
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      host: mongodb

server:
  port: 8080

