server.port: 7001
server:
  error:
    include-message: always

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: product-db

logging:
  level:
    root: INFO
    com.kimsang: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate:

---
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      host: mongodb

server.port: 8080
